### PR TITLE
"HTML5 by Default" mechanism in chrome 55 is cause of not showing flash content

### PR DESCRIPTION
**Pull request by autumnharmony**
details 
https://goo.gl/yf90nq

### CODE REVIEW

**Comment by ozzyaaron** [comment]
Thanks! This worked for us with Chrome 60.0.x

**Comment by yoriiis** [comment]
Thanks, it works perfectly !

**Comment by shadowlmd** [comment]
This patch doesn't work properly when Flash is installed but disabled in Firefox. Callback function returns success for some reason.

**Comment by ROBERT-MCDOWELL** [comment]
this should be a firefox issue or maybe new options appear to check if the plugin is enabled or not?

**Comment by GuiF73** [comment]
It works like a charm on Edge and Chrome.

**Comment by pipwerks** [comment]
Firefox no longer supports MIME type inspection, SWFObject's Flash plugin detection routine will no longer work in FF.

**Comment by ROBERT-MCDOWELL** [comment]
pipwerks:
swf must be embeded in a html page, not read directly
swfobject works in all browsers like expected

**Comment by pipwerks** [comment]
@ROBERT-MCDOWELL I'm not sure of your meaning when you say "swf must be embeded in a html page, not read directly". Of course SWFs are embedded in the page, that's SWFObject's raison d'etre. But detection scripts first check the browser's MIME types to see if the browser supports that particular file type. For SWFObject 2.3, that refers to line 54

https://github.com/swfobject/swfobject/blob/master/swfobject/src/swfobject.js#L54 

    if (d && (typeof nav.mimeTypes !== UNDEF && nav.mimeTypes[FLASH_MIME_TYPE] && nav.mimeTypes[FLASH_MIME_TYPE].enabledPlugin)) {

I just took a look at Firefox, and you are correct that SWFs still embed in Firefox. The Mozilla team implemented a workaround for Flash Player, as MIME type detection is disabled by default in FF in order to prevent browser fingerprinting. If you open the JS console in Firefox, each of the following will fail:

    navigator.mimeTypes["application/x-shockwave-flash"].enabledPlugin //undefined

    navigator.mimeTypes["application/x-shockwave-flash"] //undefined

    navigator.mimeTypes //length: 0

    navigator.plugins //length: 0

SWFObject requires each of those items for handling detection and embedding. 

However, if you have Flash Player installed, and Firefox senses the page is trying to display a Flash SWF, Firefox prompts you to allow the SWF to run on that page. If you say yes, Firefox will expose the mimeTypes array, and SWFObject will run as expected.

**Comment by ROBERT-MCDOWELL** [comment]
just said what I said for others who sometimes mess up how to read a swf in a browser.
FF is better to not break anything or for sure millions of users will switch to another browser..

**Comment by pipwerks** [comment]
Unfortunately for those who depend on Flash, support for Flash is going away very soon. Adobe is ending official support of Flash Player in 2020.

https://www.theverge.com/2017/7/25/16026236/adobe-flash-end-of-support-2020

>  Microsoft says it plans to disable Flash by default in Edge and Internet Explorer in mid to late 2019, with a full removal from all supported versions of Windows by 2020. Google will continue phasing out Flash over the next few years, while Mozilla says Firefox users will be able to choose which websites are able to run Flash next month and allow Firefox Extended Support Release (ESR) users to keep using Flash until the end of 2020. Apple is also supportive of the 2020 end of life for Flash, and Safari currently requires explicit approval on each website even when Mac users opt to install Flash.

https://theblog.adobe.com/adobe-flash-update/
https://blog.mozilla.org/futurereleases/2017/07/25/firefox-roadmap-flash-end-life/

**Comment by ROBERT-MCDOWELL** [comment]
don't waste your time, I know the story, but I repeat that all those guys won't force years of work to be unavailable on line, especially when it concerns education, corporations and companies. Flash is not about just a video or animation, it's also complex application that cannot be redeveloped simply by the fact that a bunch of browser developers decided to switch off a technology, unless if they can finance all the redevelopment. 
As I know the plugin itself will stop, but the technology will evolve with the new options (I cannot say more for now). 
Concerning Microsoft, Edge and IE11+ have already flash integrated, not as a plugin anymore.
And please don't say to switch to javascript, because it's simply impossible for some project case, and btw javascript (an older language than Flash) will end soon too.

**Comment by autumnharmony** [comment]
@pipwerks why that pull request still hadn't been merged? 
please accept that.
Many users still ~want~ need to use Flex and that library

**Comment by ROBERT-MCDOWELL** [comment]
The authors left maybe, following another fork would be better I think

**Comment by tensafefrogs** [comment]
It looks like this patch effectively disables plugin detection altogether and simply tries to write the swf to the page. As Philip mentioned, this doesn't make any sense, so we won't be merging this request.

I would be interested in ensuring that pages with a SWFObject embedded swf properly trigger the browser prompt to enable Flash (as described in the linked slides from the first comment) if this is not already the case.

**Pull request closed without merging**
